# Generated by Django 3.0.2 on 2020-01-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=50)),
                ('department_num_course', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_full_name', models.CharField(max_length=100)),
                ('teacher_username', models.CharField(max_length=50)),
                ('teacher_city', models.CharField(max_length=50)),
                ('teacher_country', models.CharField(max_length=50)),
                ('teacher_phone', models.ImageField(upload_to='')),
                ('teacher_address', models.CharField(max_length=100)),
                ('department_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Second_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('department_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Second_app.Department')),
            ],
        ),
    ]
