# Generated by Django 3.0.2 on 2020-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Second_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacher_phone',
            field=models.IntegerField(),
        ),
    ]
